'use strict';
const manual = JSON.parse(document.getElementById('manual-data').textContent);
const $ = s => document.querySelector(s);
const chat = $('#chat'), apiKey = $('#apiKey'), model = $('#model'), statusEl = $('#status'), askBtn = $('#ask'), qBox = $('#question');
const meta = manual.document || {};
$('#docMeta').innerHTML = `${escapeHtml(meta.title||'')}<br>${escapeHtml(meta.publisher||'')}<br>${escapeHtml(meta.date||'')}`;
apiKey.value = localStorage.getItem('gemini_api_key') || '';
model.value = localStorage.getItem('gemini_model') || 'gemini-3.7-flash';
if(apiKey.value) statusEl.textContent='저장된 API 키 있음';
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
function norm(s){return String(s??'').toLowerCase().replace(/,/g,'').replace(/\s+/g,' ').trim();}
function tokens(s){return [...new Set((norm(s).match(/[가-힣a-z0-9]+/g)||[]).filter(x=>x.length>=2 || /^\d+$/.test(x)))];}
const synonyms={'착공':['착공','착공계','착공신고서','시공사','제출서류'],'업체':['업체','시공사','계약상대자'],'제출서류':['제출서류','제출목록','서류'],'수의계약':['수의계약','계약','계약서'],'준공':['준공','준공계','준공검사','준공신고서'],'기성':['기성','기성검사','기성신청'],'설계':['설계','설계용역'],'감리':['감리','감리용역'],'폐기물':['폐기물','건설폐기물'],'환경보전비':['환경보전비','환경'],'안전관리비':['산업안전보건관리비','안전관리비'],'재해예방기술지도':['재해예방기술지도','기술지도']};
function expandTerms(q){const ts=tokens(q),arr=[...ts];for(const [k,vals] of Object.entries(synonyms)){if(norm(q).includes(k))arr.push(...vals);}return [...new Set(arr.map(norm))];}
function buildChunks(){const out=[];for(const ch of (manual.chapters||[])){for(const sec of (ch.sections||[])){const base=`제${ch.chapter}장 ${ch.title} > ${sec.number}. ${sec.title}`;if(sec.content?.length)out.push({id:`C${ch.chapter}-S${sec.number}`,path:base,lines:`원문 ${sec.start_line}~${sec.end_line}행`,text:sec.content.join('\n')});for(let i=0;i<(sec.subsections||[]).length;i++){const sub=sec.subsections[i];if(!sub.content?.length)continue;out.push({id:`C${ch.chapter}-S${sec.number}-SUB${i+1}`,path:`${base} > ${sub.id}. ${sub.title}`,lines:`원문 ${sub.start_line}~${sub.end_line}행`,text:sub.content.join('\n')});}}}return out;}
const chunks=buildChunks();
function retrieve(q,k=8){const terms=expandTerms(q),nq=norm(q);return chunks.map(c=>{const title=norm(c.path),text=norm(c.text),textNoComma=text.replace(/,/g,'');let score=0;for(const t0 of terms){const t=norm(t0);if(!t)continue;if(title.includes(t))score+=9;if(text.includes(t))score+=4;const n=(text.match(new RegExp(t.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'g'))||[]).length;score+=Math.min(n,5)*1.5;}for(const n of (nq.match(/\d+/g)||[])){if(textNoComma.includes(n))score+=6;}if(/착공/.test(nq)&&/착공시 제출서류|착공신고서|착공계/.test(text))score+=15;if(/제출서류/.test(nq)&&/제출서류|제출목록/.test(text))score+=12;if(/준공검사/.test(nq)&&/준공검사/.test(text))score+=15;return {...c,score};}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,k);}
function addUser(text){const el=document.createElement('div');el.className='msg user';el.innerHTML=`<div class="bubble">${escapeHtml(text)}</div>`;chat.appendChild(el);scrollEnd();}
function addLoading(){const el=document.createElement('div');el.className='msg assistant';el.id='loading';el.innerHTML='<div class="bubble"><span class="loading"><span class="dot"></span><span class="dot"></span><span class="dot"></span></span> 매뉴얼 근거를 찾고 Gemini가 답변을 작성 중입니다.</div>';chat.appendChild(el);scrollEnd();}
function scrollEnd(){chat.scrollTop=chat.scrollHeight;}
function formatAnswer(t){return escapeHtml(t).replace(/\n/g,'<br>').replace(/\*\*(.*?)\*\*/g,'<b>$1</b>');}
function renderAnswer(answer,used,note=''){document.getElementById('loading')?.remove();const el=document.createElement('div');el.className='msg assistant';const cards=used.map((s,i)=>`<div class="source-card"><div class="source-path">[근거 ${i+1}] ${escapeHtml(s.path)}</div><div class="source-lines">${escapeHtml(s.lines)} · ID ${escapeHtml(s.id)}</div><div class="source-text">${escapeHtml(s.text.length>900?s.text.slice(0,900)+'…':s.text)}</div></div>`).join('');el.innerHTML=`<div class="bubble"><div class="answer-title">답변</div>${formatAnswer(answer)}<div class="evidence"><h4>근거 조항</h4>${cards||'<div class="notice">관련 근거를 찾지 못했습니다.</div>'}${note?`<div class="notice">${escapeHtml(note)}</div>`:''}</div></div>`;chat.appendChild(el);scrollEnd();}
async function listAvailableModels(key){const res=await fetch(`https://generativelanguage.googleapis.com/v1beta/models?pageSize=1000&key=${encodeURIComponent(key)}`);const body=await res.json().catch(()=>({}));if(!res.ok)throw new Error(body?.error?.message||`모델 목록 조회 실패 (${res.status})`);return (body.models||[]).filter(m=>(m.supportedGenerationMethods||[]).includes('generateContent'));}
function modelPriority(id){const s=id.toLowerCase();let p=100;if(s.includes('flash-lite'))p-=40;else if(s.includes('flash'))p-=30;else if(s.includes('pro'))p-=10;if(s.includes('2.5'))p-=8;if(s.includes('2.0'))p-=4;if(s.includes('preview'))p+=20;if(s.includes('exp'))p+=30;return p;}
async function refreshModels(){const key=apiKey.value.trim();if(!key)throw new Error('Gemini API 키를 입력하세요.');const models=await listAvailableModels(key);if(!models.length)throw new Error('generateContent 가능한 모델을 찾지 못했습니다.');const ids=[...new Set(models.map(m=>(m.baseModelId||m.name||'').replace(/^models\//,'')).filter(Boolean))];const ordered=[...ids].sort((a,b)=>modelPriority(a)-modelPriority(b)||a.localeCompare(b));const saved=localStorage.getItem('gemini_model');const selected=(saved&&ordered.includes(saved))?saved:ordered[0];model.innerHTML='';for(const id of ordered){const op=document.createElement('option');op.value=id;op.textContent=models.find(m=>(m.baseModelId||m.name||'').replace(/^models\//,'')===id)?.displayName||id;model.appendChild(op);}model.value=selected;localStorage.setItem('gemini_model',selected);return selected;}
function sleep(ms){return new Promise(r=>setTimeout(r,ms));}
function isTemporaryGeminiError(status,msg=''){const m=String(msg).toLowerCase();return [429,500,502,503,504].includes(status)||/high demand|overloaded|temporar|resource exhausted|unavailable|try again later|quota.*tempor/i.test(m);}
async function callGemini(question,sources){const key=apiKey.value.trim();if(!key)throw new Error('Gemini API 키를 입력하세요.');const srcText=sources.map((s,i)=>`[근거 ${i+1}]\nID: ${s.id}\n위치: ${s.path}\n${s.lines}\n원문:\n${s.text}`).join('\n\n---\n\n');const prompt=`당신은 학교시설공사 행정업무 질의응답 도우미다. 아래 제공된 매뉴얼 발췌만 근거로 답하라. 핵심 결론→항목별 설명 순서로 답하고 각 핵심 문장 끝에 [근거 N]을 붙인다. 한국어로 답한다.\n\n질문: ${question}\n\n매뉴얼 발췌:\n${srcText}`;if(!model.options.length)await refreshModels();const all=[...model.options].map(o=>o.value),selected=model.value,candidates=[selected,...all.filter(x=>x!==selected)],failures=[];for(const modelId of candidates){for(let attempt=1;attempt<=3;attempt++){const endpoint=`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(modelId)}:generateContent?key=${encodeURIComponent(key)}`;let res,body={};try{res=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contents:[{role:'user',parts:[{text:prompt}]}],generationConfig:{temperature:0.2,maxOutputTokens:1800}})});body=await res.json().catch(()=>({}));}catch(e){failures.push(`${modelId}: 네트워크 오류`);if(attempt<3){await sleep(800*attempt);continue;}break;}if(res.ok){const out=(body.candidates?.[0]?.content?.parts||[]).map(p=>p.text||'').join('').trim();if(out){if(model.value!==modelId){model.value=modelId;localStorage.setItem('gemini_model',modelId);}return {text:out,modelId,switched:modelId!==selected};}}const msg=body?.error?.message||`Gemini API 오류 (${res.status})`;failures.push(`${modelId}: ${msg}`);if(isTemporaryGeminiError(res.status,msg)&&attempt<3){await sleep(900*Math.pow(2,attempt-1));continue;}if([400,401,403].includes(res.status))throw new Error(msg);break;}}throw new Error('사용 가능한 Gemini 모델들로 재시도했지만 응답을 받지 못했습니다. '+failures.slice(-5).join(' | '));}
function citedSources(answer,sources){const ns=[...answer.matchAll(/\[근거\s*(\d+)\]/g)].map(m=>Number(m[1])-1),uniq=[...new Set(ns)].filter(i=>i>=0&&i<sources.length);return uniq.length?uniq.map(i=>sources[i]):sources.slice(0,3);}
async function ask(){const q=qBox.value.trim();if(!q)return;if(!apiKey.value.trim()){alert('먼저 Gemini API 키를 입력해 주세요.');apiKey.focus();return;}addUser(q);qBox.value='';askBtn.disabled=true;addLoading();let sources=[];try{sources=retrieve(q,8);if(!sources.length){renderAnswer('첨부 매뉴얼에서 질문과 직접 연결되는 근거를 찾지 못했습니다.',[]);return;}const result=await callGemini(q,sources);renderAnswer(result.text,citedSources(result.text,sources),result.switched?`응답 모델 자동 전환: ${result.modelId}`:`응답 모델: ${result.modelId}`);}catch(e){document.getElementById('loading')?.remove();renderAnswer(`Gemini 답변 생성에 실패했습니다.\n\n${e.message}`,sources.slice(0,4),'매뉴얼 검색 결과는 유지됩니다.');}finally{askBtn.disabled=false;qBox.focus();}}
$('#saveKey').addEventListener('click',()=>{const k=apiKey.value.trim();if(k){localStorage.setItem('gemini_api_key',k);localStorage.setItem('gemini_model',model.value);statusEl.textContent='API 키 저장됨';}else{localStorage.removeItem('gemini_api_key');statusEl.textContent='API 키 삭제됨';}});
$('#testKey').addEventListener('click',async()=>{if(!apiKey.value.trim()){alert('API 키를 입력하세요.');return;}statusEl.textContent='연결 확인 중…';try{const selected=await refreshModels();statusEl.textContent=`연결 성공 · ${model.options.length}개 모델 · 기본 ${selected}`;statusEl.style.color='var(--ok)';}catch(e){statusEl.textContent='연결 실패';statusEl.style.color='#b91c1c';alert('연결 실패\n\n'+e.message);}});
askBtn.addEventListener('click',ask);qBox.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();ask();}});model.addEventListener('change',()=>localStorage.setItem('gemini_model',model.value));document.addEventListener('click',e=>{const b=e.target.closest('[data-q]');if(b){qBox.value=b.dataset.q;qBox.focus();}});